// AUTO-GENERATED by maintenance/medicine-list-generator/src/update_medications.py
// Do not edit manually. Regenerate: python src/update_medications.py

export type DrugClass =
  | 'NSAID'
  | 'Opioid'
  | 'Muscle Relaxant'
  | 'Anticonvulsant'
  | 'Adjuvant'
  | 'Combination'
  | 'Other';

export interface MedCatalogEntry {
  rxcui:       string;
  genericName: string;
  brandNames:  string[];
  strengths:   string[];
  routes:      string[];
  drugClass:   DrugClass;
}

// 75 entries
export const MEDICATION_CATALOG: MedCatalogEntry[] = [
  { rxcui: "161", genericName: "acetaminophen", brandNames: ["Tylenol", "Tylenol Extra Strength"], strengths: ["325 mg", "500 mg", "650 mg", "1000 mg"], routes: ["injectable", "oral", "rectal", "topical"], drugClass: "Other" },
  { rxcui: "519", genericName: "allopurinol", brandNames: ["Aloprim"], strengths: ["100 mg", "200 mg", "300 mg", "500 mg"], routes: ["injectable", "oral"], drugClass: "Other" },
  { rxcui: "203168", genericName: "amitriptyline", brandNames: [], strengths: ["10 mg", "25 mg", "50 mg", "75 mg", "100 mg", "150 mg"], routes: ["oral"], drugClass: "Adjuvant" },
  { rxcui: "1191", genericName: "aspirin", brandNames: [], strengths: ["81 mg", "325 mg", "500 mg", "650 mg"], routes: ["oral", "rectal", "topical"], drugClass: "NSAID" },
  { rxcui: "466584", genericName: "aspirin / acetaminophen / caffeine", brandNames: ["Excedrin Extra Strength", "Excedrin Migraine", "Excedrin Tension Headache"], strengths: ["250 mg / 250 mg / 65 mg"], routes: ["oral"], drugClass: "Combination" },
  { rxcui: "1292", genericName: "baclofen", brandNames: ["Fleqsuvy", "Gablofen", "Lyvispah", "Ozobax DS"], strengths: ["5 mg", "10 mg", "20 mg"], routes: ["oral"], drugClass: "Muscle Relaxant" },
  { rxcui: "1819", genericName: "buprenorphine", brandNames: ["Belbuca", "Brixadi", "Butrans", "Sublocade"], strengths: ["1 mg", "1.4 mg", "2 mg", "2.1 mg", "2.9 mg", "3 mg", "4 mg", "5.7 mg", "8 mg", "8.6 mg", "11.4 mg", "12 mg", "16 mg", "24 mg", "32 mg", "64 mg", "96 mg", "100 mg", "128 mg", "300 mg"], routes: ["injectable", "sublingual", "transdermal"], drugClass: "Opioid" },
  { rxcui: "1841", genericName: "butorphanol", brandNames: [], strengths: ["10 mg/ml"], routes: ["injectable", "nasal"], drugClass: "Opioid" },
  { rxcui: "1992", genericName: "capsaicin", brandNames: [], strengths: ["4 mg", "10 mg", "27.5 mg", "50 mg/ml", "200 mg/ml"], routes: ["oral", "topical", "transdermal"], drugClass: "Other" },
  { rxcui: "2002", genericName: "carbamazepine", brandNames: ["Carbatrol", "Equetro", "Tegretol", "Tegretol XR"], strengths: ["100 mg", "200 mg", "300 mg", "400 mg"], routes: ["oral"], drugClass: "Anticonvulsant" },
  { rxcui: "2101", genericName: "carisoprodol", brandNames: ["Soma"], strengths: ["250 mg", "350 mg"], routes: ["oral"], drugClass: "Muscle Relaxant" },
  { rxcui: "140587", genericName: "celecoxib", brandNames: ["Celebrex", "Vyscoxa"], strengths: ["100 mg", "200 mg", "400 mg"], routes: ["oral"], drugClass: "NSAID" },
  { rxcui: "2410", genericName: "chlorzoxazone", brandNames: [], strengths: ["250 mg", "375 mg", "500 mg", "750 mg"], routes: ["oral"], drugClass: "Muscle Relaxant" },
  { rxcui: "2597", genericName: "clomipramine", brandNames: ["Anafranil"], strengths: ["25 mg", "50 mg", "75 mg"], routes: ["oral"], drugClass: "Adjuvant" },
  { rxcui: "1008493", genericName: "codeine", brandNames: [], strengths: ["6.25 mg", "8 mg", "10 mg", "15 mg", "30 mg", "40 mg", "50 mg", "54.3 mg", "60 mg", "100 mg", "300 mg", "325 mg"], routes: ["oral"], drugClass: "Opioid" },
  { rxcui: "2683", genericName: "colchicine", brandNames: ["Colcrys", "Gloperba", "Lodoco", "Mitigare"], strengths: ["500 mg"], routes: ["oral"], drugClass: "Other" },
  { rxcui: "21949", genericName: "cyclobenzaprine", brandNames: ["Amrix", "Tonmya"], strengths: ["5 mg", "7.5 mg", "10 mg"], routes: ["oral", "sublingual"], drugClass: "Muscle Relaxant" },
  { rxcui: "3105", genericName: "dantrolene", brandNames: ["Dantrium"], strengths: ["20 mg", "25 mg", "50 mg", "100 mg", "250 mg"], routes: ["injectable", "oral"], drugClass: "Muscle Relaxant" },
  { rxcui: "203174", genericName: "desipramine", brandNames: ["Norpramin"], strengths: ["10 mg", "25 mg", "50 mg", "75 mg", "100 mg", "150 mg"], routes: ["oral"], drugClass: "Adjuvant" },
  { rxcui: "22690", genericName: "dexamethasone", brandNames: ["Dextenza", "Dexycu", "Hemady", "Maxidex", "Ozurdex"], strengths: ["1 mg/ml", "1 mg", "1.5 mg", "2 mg", "3 mg/ml", "3 mg", "3.5 mg/ml", "3.5 mg", "4 mg", "4 mg/ml", "6 mg", "10 mg/ml", "20 mg", "100 mg"], routes: ["injectable", "ophthalmic", "oral", "topical"], drugClass: "Other" },
  { rxcui: "3355", genericName: "diclofenac", brandNames: ["Cambia", "Flector", "Licart", "Voltaren Arthritis Pain", "Zipsor"], strengths: ["25 mg", "50 mg", "75 mg", "100 mg"], routes: ["ophthalmic", "oral", "topical", "transdermal"], drugClass: "NSAID" },
  { rxcui: "3393", genericName: "diflunisal", brandNames: [], strengths: ["500 mg"], routes: ["oral"], drugClass: "NSAID" },
  { rxcui: "476250", genericName: "duloxetine", brandNames: ["Cymbalta", "Drizalma Sprinkle"], strengths: ["20 mg", "30 mg", "60 mg"], routes: ["oral"], drugClass: "Adjuvant" },
  { rxcui: "24605", genericName: "etodolac", brandNames: [], strengths: ["200 mg", "300 mg", "400 mg", "500 mg", "600 mg"], routes: ["oral"], drugClass: "NSAID" },
  { rxcui: "4331", genericName: "fenoprofen", brandNames: [], strengths: ["300 mg", "400 mg"], routes: ["oral"], drugClass: "NSAID" },
  { rxcui: "4502", genericName: "flurbiprofen", brandNames: [], strengths: ["100 mg"], routes: ["ophthalmic", "oral"], drugClass: "NSAID" },
  { rxcui: "4511", genericName: "folic acid", brandNames: ["Quiofic"], strengths: ["1 mg", "1.05 mg", "1.2 mg", "1.3 mg", "1.4 mg", "1.5 mg", "1.7 mg", "1.8 mg", "1.84 mg", "2 mg", "2.3 mg", "2.5 mg", "2.6 mg", "3 mg", "3.25 mg", "3.35 mg", "3.4 mg", "5 mg", "6 mg", "9 mg", "10 mg", "12 mg", "13 mg", "13.5 mg", "15 mg", "17 mg", "20 mg", "22.5 mg", "24.5 mg", "25 mg", "26 mg", "27 mg", "28 mg", "30 mg", "37.5 mg", "40 mg", "45 mg", "50 mg", "55 mg", "60 mg", "75 mg", "80 mg", "85 mg", "90 mg", "100 mg", "120 mg", "125 mg", "155 mg", "200 mg", "250 mg", "300 mg", "500 mg"], routes: ["injectable", "oral", "sublingual"], drugClass: "Other" },
  { rxcui: "25480", genericName: "gabapentin", brandNames: ["Gralise", "Horizant", "Neurontin"], strengths: ["100 mg", "300 mg", "400 mg", "600 mg", "800 mg"], routes: ["oral"], drugClass: "Anticonvulsant" },
  { rxcui: "142439", genericName: "hydrocodone", brandNames: ["Hysingla ER"], strengths: ["5 mg", "7.5 mg", "10 mg"], routes: ["oral"], drugClass: "Opioid" },
  { rxcui: "857005", genericName: "hydrocodone / acetaminophen", brandNames: ["Vicodin", "Norco", "Lortab"], strengths: ["5 mg / 300 mg", "5 mg / 325 mg", "7.5 mg / 325 mg", "10 mg / 325 mg"], routes: ["oral"], drugClass: "Combination" },
  { rxcui: "203177", genericName: "hydromorphone", brandNames: ["Dilaudid"], strengths: ["1 mg/ml", "2 mg/ml", "2 mg", "4 mg", "4 mg/ml", "5 mg", "8 mg", "10 mg/ml", "12 mg", "16 mg", "32 mg"], routes: ["injectable", "oral", "rectal"], drugClass: "Opioid" },
  { rxcui: "153972", genericName: "hydroxychloroquine", brandNames: ["Plaquenil", "Sovuna"], strengths: ["200 mg", "300 mg"], routes: ["oral"], drugClass: "Other" },
  { rxcui: "5640", genericName: "ibuprofen", brandNames: ["Advil", "Advil Liqui-gels", "Advil Liquigel", "Advil Migraine", "Motrin IB", "Neoprofen"], strengths: ["200 mg", "400 mg", "600 mg", "800 mg"], routes: ["injectable", "oral", "topical"], drugClass: "NSAID" },
  { rxcui: "835564", genericName: "ibuprofen / diphenhydramine", brandNames: ["Advil PM", "Motrin PM"], strengths: ["200 mg / 25 mg"], routes: ["oral"], drugClass: "Combination" },
  { rxcui: "150816", genericName: "imipramine", brandNames: [], strengths: ["10 mg", "25 mg", "50 mg"], routes: ["oral"], drugClass: "Adjuvant" },
  { rxcui: "5781", genericName: "indomethacin", brandNames: ["Indocin"], strengths: ["1 mg/ml", "25 mg", "50 mg", "75 mg"], routes: ["injectable", "oral", "rectal"], drugClass: "NSAID" },
  { rxcui: "6142", genericName: "ketoprofen", brandNames: [], strengths: ["75 mg"], routes: ["oral"], drugClass: "NSAID" },
  { rxcui: "35827", genericName: "ketorolac", brandNames: ["Acular", "Acular Ls", "Acuvail", "Sprix"], strengths: ["2.88 mg/ml", "4 mg/ml", "4.5 mg/ml", "5 mg/ml", "10 mg", "10.16 mg/ml", "15 mg/ml", "15.75 mg", "30 mg/ml", "60 mg"], routes: ["injectable", "nasal", "ophthalmic", "oral", "topical"], drugClass: "NSAID" },
  { rxcui: "623400", genericName: "lacosamide", brandNames: ["Motpoly XR", "Vimpat"], strengths: ["10 mg/ml", "50 mg", "100 mg", "150 mg", "200 mg"], routes: ["injectable", "oral"], drugClass: "Anticonvulsant" },
  { rxcui: "28439", genericName: "lamotrigine", brandNames: ["Lamictal", "Lamictal Odt", "Lamictal XR", "Subvenite"], strengths: ["2 mg", "5 mg", "10 mg/ml", "25 mg", "50 mg", "100 mg", "150 mg", "200 mg", "250 mg", "300 mg"], routes: ["oral"], drugClass: "Anticonvulsant" },
  { rxcui: "6378", genericName: "levorphanol", brandNames: [], strengths: ["2 mg"], routes: ["oral"], drugClass: "Opioid" },
  { rxcui: "142440", genericName: "lidocaine", brandNames: ["Akten", "Xylocaine", "Xylocaine Mpf", "Zingo", "Ztlido"], strengths: ["1.3 mg", "2 mg/ml", "2.5 mg", "4 mg", "5 mg", "5 mg/ml", "7 mg/ml", "8 mg", "8 mg/ml", "10 mg/ml", "10 mg", "15 mg", "15 mg/ml", "20 mg", "20 mg/ml", "25 mg", "28 mg", "30 mg", "35 mg/ml", "36 mg", "38.8 mg", "40 mg/ml", "40 mg", "41.2 mg", "50 mg/ml", "50 mg", "60 mg", "70 mg", "100 mg", "170 mg", "240 mg", "400 mg", "600 mg", "700 mg", "3400 mg"], routes: ["injectable", "ophthalmic", "oral", "rectal", "topical", "transdermal"], drugClass: "Other" },
  { rxcui: "6693", genericName: "mefenamic acid", brandNames: [], strengths: ["250 mg"], routes: ["oral"], drugClass: "NSAID" },
  { rxcui: "41493", genericName: "meloxicam", brandNames: ["Qamzova", "Xifyrm", "Zybic"], strengths: ["50 mg", "100 mg", "150 mg", "200 mg", "300 mg"], routes: ["injectable", "oral"], drugClass: "NSAID" },
  { rxcui: "103755", genericName: "meperidine", brandNames: ["Demerol"], strengths: ["25 mg/ml", "50 mg/ml", "50 mg", "75 mg/ml"], routes: ["injectable", "oral"], drugClass: "Opioid" },
  { rxcui: "59078", genericName: "metaxalone", brandNames: [], strengths: ["400 mg", "640 mg", "800 mg"], routes: ["oral"], drugClass: "Muscle Relaxant" },
  { rxcui: "218337", genericName: "methadone", brandNames: ["Diskets", "Methadose", "Methadose Sugar-free"], strengths: ["5 mg", "10 mg", "10 mg/ml", "40 mg"], routes: ["injectable", "oral"], drugClass: "Opioid" },
  { rxcui: "6845", genericName: "methocarbamol", brandNames: ["Atmeksi", "Robaxin"], strengths: ["100 mg/ml", "500 mg", "750 mg", "1000 mg"], routes: ["injectable", "oral"], drugClass: "Muscle Relaxant" },
  { rxcui: "6851", genericName: "methotrexate", brandNames: ["Jylamvo", "Otrexup", "Rasuvo", "Xatmep"], strengths: ["2 mg/ml", "2.5 mg", "2.5 mg/ml", "7.5 mg", "10 mg", "12.5 mg", "15 mg", "17.5 mg", "20 mg", "22.5 mg", "25 mg", "25 mg/ml", "30 mg"], routes: ["injectable", "oral"], drugClass: "Other" },
  { rxcui: "155323", genericName: "methylprednisolone", brandNames: ["Depo-medrol", "Medrol", "Solu-medrol"], strengths: ["2 mg", "4 mg", "8 mg", "16 mg", "20 mg/ml", "32 mg", "40 mg", "40 mg/ml", "80 mg/ml", "125 mg", "500 mg", "500 mg/ml"], routes: ["injectable", "oral", "topical"], drugClass: "Other" },
  { rxcui: "30003", genericName: "milnacipran", brandNames: ["Savella"], strengths: ["12.5 mg", "25 mg", "50 mg", "100 mg"], routes: ["oral"], drugClass: "Adjuvant" },
  { rxcui: "235751", genericName: "morphine", brandNames: ["Duramorph", "Infumorph 200", "Infumorph 500", "Ms Contin"], strengths: ["1 mg/ml", "2 mg/ml", "4 mg/ml", "5 mg/ml", "8 mg/ml", "10 mg", "10 mg/ml", "15 mg", "20 mg", "20 mg/ml", "25 mg/ml", "30 mg", "50 mg/ml", "50 mg", "60 mg", "80 mg", "100 mg", "200 mg"], routes: ["injectable", "oral", "rectal"], drugClass: "Opioid" },
  { rxcui: "31448", genericName: "nabumetone", brandNames: [], strengths: ["500 mg", "750 mg"], routes: ["oral"], drugClass: "NSAID" },
  { rxcui: "154985", genericName: "nalbuphine", brandNames: [], strengths: ["10 mg/ml", "20 mg/ml"], routes: ["injectable"], drugClass: "Opioid" },
  { rxcui: "7258", genericName: "naproxen", brandNames: ["Aleve", "Aleve Caplets", "Aleve Easy Open Arthritis", "Aleve Gelcaps", "Aleve Headache Pain", "Aleve, Travel Basix", "Bayer Aleve", "Naprelan"], strengths: ["220 mg", "250 mg", "375 mg", "500 mg"], routes: ["oral"], drugClass: "NSAID" },
  { rxcui: "203130", genericName: "nortriptyline", brandNames: ["Pamelor"], strengths: ["10 mg", "25 mg", "50 mg", "75 mg"], routes: ["oral"], drugClass: "Adjuvant" },
  { rxcui: "202723", genericName: "orphenadrine", brandNames: [], strengths: ["50 mg", "60 mg", "100 mg", "770 mg"], routes: ["injectable", "oral"], drugClass: "Muscle Relaxant" },
  { rxcui: "32613", genericName: "oxaprozin", brandNames: ["Coxanto", "Daypro"], strengths: ["300 mg", "600 mg"], routes: ["oral"], drugClass: "NSAID" },
  { rxcui: "32624", genericName: "oxcarbazepine", brandNames: ["Oxtellar XR", "Trileptal"], strengths: ["60 mg/ml", "150 mg", "300 mg", "600 mg"], routes: ["oral"], drugClass: "Anticonvulsant" },
  { rxcui: "7804", genericName: "oxycodone", brandNames: ["Oxaydo", "Oxycontin", "Roxicodone", "Roxybond", "Xtampza ER"], strengths: ["5 mg", "10 mg", "15 mg", "20 mg", "30 mg", "40 mg", "80 mg"], routes: ["oral"], drugClass: "Opioid" },
  { rxcui: "724614", genericName: "oxycodone / acetaminophen", brandNames: ["Percocet", "Endocet", "Roxicet"], strengths: ["5 mg / 325 mg", "7.5 mg / 325 mg", "10 mg / 325 mg"], routes: ["oral"], drugClass: "Combination" },
  { rxcui: "7814", genericName: "oxymorphone", brandNames: [], strengths: ["5 mg", "7.5 mg", "10 mg", "15 mg", "20 mg", "30 mg", "40 mg"], routes: ["oral"], drugClass: "Opioid" },
  { rxcui: "104973", genericName: "pentazocine", brandNames: [], strengths: ["50 mg"], routes: ["oral"], drugClass: "Opioid" },
  { rxcui: "8356", genericName: "piroxicam", brandNames: [], strengths: ["10 mg", "20 mg"], routes: ["oral"], drugClass: "NSAID" },
  { rxcui: "8640", genericName: "prednisone", brandNames: [], strengths: ["1 mg", "2 mg", "2.5 mg", "5 mg", "10 mg", "20 mg", "50 mg"], routes: ["oral"], drugClass: "Other" },
  { rxcui: "187832", genericName: "pregabalin", brandNames: ["Lyrica", "Lyrica CR"], strengths: ["25 mg", "50 mg", "75 mg", "100 mg", "150 mg", "200 mg", "225 mg", "300 mg"], routes: ["oral"], drugClass: "Anticonvulsant" },
  { rxcui: "8698", genericName: "probenecid", brandNames: [], strengths: ["500 mg"], routes: ["oral"], drugClass: "Other" },
  { rxcui: "10237", genericName: "sulindac", brandNames: [], strengths: ["150 mg", "200 mg"], routes: ["oral"], drugClass: "NSAID" },
  { rxcui: "787390", genericName: "tapentadol", brandNames: ["Nucynta", "Nucynta ER"], strengths: ["50 mg", "75 mg", "100 mg", "150 mg", "200 mg", "250 mg"], routes: ["oral"], drugClass: "Opioid" },
  { rxcui: "236460", genericName: "tizanidine", brandNames: ["Ontralfy", "Zanaflex"], strengths: ["2 mg", "4 mg", "6 mg", "8 mg"], routes: ["oral"], drugClass: "Muscle Relaxant" },
  { rxcui: "10636", genericName: "tolmetin", brandNames: [], strengths: ["400 mg", "600 mg"], routes: ["oral"], drugClass: "NSAID" },
  { rxcui: "38404", genericName: "topiramate", brandNames: ["Eprontia", "Qudexy XR", "Topamax", "Trokendi XR"], strengths: ["3.75 mg", "7.5 mg", "11.25 mg", "15 mg", "23 mg", "25 mg", "25 mg/ml", "46 mg", "50 mg", "69 mg", "92 mg", "100 mg", "150 mg", "200 mg"], routes: ["oral"], drugClass: "Anticonvulsant" },
  { rxcui: "10689", genericName: "tramadol", brandNames: ["Conzip"], strengths: ["5 mg/ml", "37.5 mg", "50 mg", "100 mg", "200 mg", "300 mg", "325 mg"], routes: ["oral"], drugClass: "Opioid" },
  { rxcui: "11118", genericName: "valproic acid", brandNames: [], strengths: ["250 mg", "500 mg"], routes: ["oral"], drugClass: "Anticonvulsant" },
  { rxcui: "235988", genericName: "venlafaxine", brandNames: ["Effexor XR"], strengths: ["25 mg", "37.5 mg", "50 mg", "75 mg", "100 mg", "112.5 mg", "150 mg", "225 mg"], routes: ["oral"], drugClass: "Adjuvant" },
];
